feat: report method name in WS metrics
ethereum-optimism/infra pull request #29
Opened 2024-07-19 12:45 UTC by mkykadir

**Description**

Access method name in WS context so metrics can be reported with method name

2024-07-26 18:33 UTC, jelias2 commented
Hi Mkykadir,

Thanks for the contribution!

Its a clever solution, however I am concerned about a race condition occurring with concurrent map access w.reqIdToMethod if the proxyd was under heavy ws traffic. 

I'm curious if you would be able to find a solution that can avoid this? 

Also please include test cases if possible

2024-07-26 18:34 UTC, jelias2 requested changes
In the PRs current state with concurrent map access, I believe these concerns must be addressed before merging

2024-08-05 19:32 UTC, mkykadir commented
@jelias2 nice catches actually I missed a crucial point as well:
* reqId within context is determined on WS connection and shouldn't be used for all following ws messages
* now each ws connection will have its own concurrent map
* and following message ids will be used for this
* after its ok for you I'll go with tests as well

2025-01-08 01:02 UTC, jelias2 commented on proxyd/string_map.go
> +package proxyd
Some tests for this struct to validate concurrency would nice

2025-01-08 01:04 UTC, jelias2 commented on proxyd/backend.go
> +			if value, has := idToMethod.GetAndRemove(string(res.ID)); has {
Will res.ID be unique? Typically is determined by the request ID with in the rpc, I don't believe its unique among many requests?

2025-03-05 07:53 UTC, closed without merging